"""
HICE Detection Framework — Research Dashboard
FastAPI backend with server-rendered HTML + Plotly.js frontend.
Data loaded from pre-computed JSON (generated by scripts/precompute.py).
"""
import os, json, re, pathlib
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

HERE = pathlib.Path(__file__).parent

app = FastAPI(title="HICE Detection Framework")
app.mount("/static", StaticFiles(directory=str(HERE / "static")), name="static")
templates = Jinja2Templates(directory=str(HERE / "templates"))

HICE_COLORS = {
    "infrastructure_damage": "#2563eb",
    "access_disruption": "#7c3aed",
    "personnel_targeting": "#dc2626",
    "humanitarian_disruption": "#64748b",
    "systemic_attack": "#0891b2",
}
HICE_LABELS = {
    "infrastructure_damage": "Infrastructure Damage",
    "access_disruption": "Access Disruption",
    "personnel_targeting": "Personnel Targeting",
    "humanitarian_disruption": "Humanitarian Disruption",
    "systemic_attack": "Systemic Attack",
}


# ── Load pre-computed dashboard data ───────────────────────────────
data = json.load(open(HERE / "data" / "dashboard_data.json"))

meta = data["meta"]
overview_data = (data["overview"]["pie"], data["overview"]["kw"], data["overview"]["actor"], data["overview"]["evt"])
geo_data = json.dumps(data["geo"])
temporal_data = (data["temporal"]["trend"], data["temporal"]["cat"], data["temporal"]["cum"])
risk_data = (data["risk"]["severity"], data["risk"]["matrix"], data["risk"]["vuln"], data["risk"]["table"])
records_data = data["records"]
categories = data["categories"]

total_events = meta["total_events"]
total_hice = meta["total_hice"]
date_min = meta["date_min"]
date_max = meta["date_max"]


# ── Pipeline Simulator ──────────────────────────────────────────────────

def find_matches(regex_list: list[str], text: str) -> list[dict]:
    results = []
    for pat in regex_list:
        for m in re.finditer(pat, text):
            results.append({
                "pattern": pat,
                "start": m.start(),
                "end": m.end(),
                "match_text": m.group(),
            })
    return results


def find_proximity_matches(text: str, health_regex: str, attack_regex: str, window: int) -> list[dict]:
    results = []
    pat1 = rf'({health_regex}.{{0,{window}}}{attack_regex})'
    for m in re.finditer(pat1, text):
        results.append({
            "pattern": "health_near_attack",
            "start": m.start(), "end": m.end(),
            "match_text": m.group(),
        })
    pat2 = rf'({attack_regex}.{{0,{window}}}{health_regex})'
    for m in re.finditer(pat2, text):
        results.append({
            "pattern": "attack_near_health",
            "start": m.start(), "end": m.end(),
            "match_text": m.group(),
        })
    return results


def simulate_pipeline(text: str) -> dict:
    """Run a single narrative through the full HICE detection pipeline and return step-by-step results."""
    import pandas as pd
    from src.hice_detector import (
        HEALTH_TERMS, TARGETING_PATTERN, ACTION_PHRASES,
        SOFT_HEALTH_PATTERN, HEALTH_INFRA, ATTACK_TERMS,
        PROXIMITY_WINDOW,
        ENUMERATION_FP_PATTERN, ENUMERATION_FP_NEGATIVE,
        HOSPITAL_BYSTANDER_PATTERN, HOSPITAL_BYSTANDER_NEGATIVE,
    )

    lower = text.lower().strip()
    if not lower:
        return {"error": "No text provided"}

    steps = []

    kinetic_pattern = r'\b(attack(ed|ing)?|shell(ed|ing)?|bomb(ed|ing)?|raid(ed|ing)?|assault(ed|ing)?|fired?\s+(upon|on|at)|clash(ed|ing)?|fought?|fighting|gunfire|shoot(ing)?|shot|explosion|airstrike|artillery|mortar|rocket|grenade)\b'
    actor_pattern = r'\b(military|soldier(s)?|junta|tatmadaw|armed\s+forces|police|security\s+forces|rebels?|resistance|militia|armed\s+group|army|troops|gunmen)\b'
    kinetic_matches = find_matches([kinetic_pattern], lower)
    actor_matches = find_matches([actor_pattern], lower)
    structural_pass = len(kinetic_matches) > 0 and len(actor_matches) > 0
    steps.append({
        "id": "structural_gate",
        "label": "Structural Gate (Layer 1)",
        "desc": "Kinetic conflict event with identified armed actor",
        "passed": structural_pass,
        "matches": kinetic_matches + actor_matches,
        "subchecks": [
            {"label": "Kinetic event language (attack, shell, raid, etc.)", "passed": len(kinetic_matches) > 0},
            {"label": "Armed actor identified (military, police, militia, etc.)", "passed": len(actor_matches) > 0},
        ],
    })

    health_matches = find_matches(HEALTH_TERMS, lower)
    steps.append({
        "id": "health_mask",
        "label": "Health Keyword Detection",
        "desc": "Mentions health infrastructure, personnel, or organisations",
        "passed": len(health_matches) > 0,
        "matches": health_matches,
    })

    targeting_matches = find_matches([TARGETING_PATTERN], lower)
    steps.append({
        "id": "targeting_mask",
        "label": "Targeting Language",
        "desc": "Explicit targeting verbs (targeted, fired upon, raided, etc.)",
        "passed": len(targeting_matches) > 0,
        "matches": targeting_matches,
    })

    phrase_matches = find_matches(ACTION_PHRASES, lower)
    steps.append({
        "id": "phrase_mask",
        "label": "Action Phrases",
        "desc": "Passive-voice hostile action phrases (was destroyed, came under fire, etc.)",
        "passed": len(phrase_matches) > 0,
        "matches": phrase_matches,
    })

    soft_matches = find_matches([SOFT_HEALTH_PATTERN], lower)
    steps.append({
        "id": "soft_health",
        "label": "Soft Health-Casualty Coupling",
        "desc": "Casualty language near health personnel",
        "passed": len(soft_matches) > 0,
        "matches": soft_matches,
    })

    proximity_matches = find_proximity_matches(lower, HEALTH_INFRA, ATTACK_TERMS, PROXIMITY_WINDOW)
    steps.append({
        "id": "proximity",
        "label": "Bidirectional Proximity Coupling",
        "desc": f"Health term and attack verb co-occur within {PROXIMITY_WINDOW} characters",
        "passed": len(proximity_matches) > 0,
        "matches": proximity_matches,
    })

    enum_fp_matches = find_matches([ENUMERATION_FP_PATTERN], lower)
    enum_neg_matches = find_matches([ENUMERATION_FP_NEGATIVE], lower)
    hospital_bystander_matches = find_matches([HOSPITAL_BYSTANDER_PATTERN], lower)
    hospital_bystander_neg_matches = find_matches([HOSPITAL_BYSTANDER_NEGATIVE], lower)

    enumeration_bystander = len(enum_fp_matches) > 0 and len(enum_neg_matches) == 0
    hospital_bystander = len(hospital_bystander_matches) > 0 and len(hospital_bystander_neg_matches) == 0
    bystander_flagged = enumeration_bystander or hospital_bystander

    steps.append({
        "id": "bystander",
        "label": "Bystander Disambiguation (F1–F4)",
        "desc": "Excludes false positives where health terms are background context",
        "passed": not bystander_flagged,
        "matches": enum_fp_matches + hospital_bystander_matches,
        "bystander_flagged": bystander_flagged,
        "subchecks": [
            {
                "label": "F1/F4 — Enumeration FP",
                "pattern": "civilian casualty list with health terms but no attack",
                "passed": not (len(enum_fp_matches) > 0 and len(enum_neg_matches) == 0),
                "matched": len(enum_fp_matches) > 0 and len(enum_neg_matches) == 0,
            },
            {
                "label": "F3 — Spatial-only Proximity",
                "pattern": "taken/sent to hospital as location, not attack target",
                "passed": not (len(hospital_bystander_matches) > 0 and len(hospital_bystander_neg_matches) == 0),
                "matched": len(hospital_bystander_matches) > 0 and len(hospital_bystander_neg_matches) == 0,
            },
        ],
    })

    proximity_ok = len(proximity_matches) > 0
    phrase_ok = len(phrase_matches) > 0
    soft_ok = len(soft_matches) > 0
    targeting_ok = len(targeting_matches) > 0
    coupling = (proximity_ok or phrase_ok or soft_ok or targeting_ok) and not bystander_flagged

    steps.append({
        "id": "coupling",
        "label": "Event Coupling Decision",
        "desc": "Hostile signal present AND not excluded by bystander rules",
        "passed": coupling,
        "subchecks": [
            {"label": "Any signal (proximity / phrase / soft / targeting)", "passed": proximity_ok or phrase_ok or soft_ok or targeting_ok},
            {"label": "Not excluded by bystander", "passed": not bystander_flagged},
        ],
    })

    health_ok = len(health_matches) > 0
    is_hice = (health_ok or proximity_ok) and coupling

    if is_hice:
        from src.hice_detector import classify_hice_type as classify_series_fn
        dummy_series = pd.Series([lower])
        hice_type_arr = classify_series_fn(dummy_series)
        hice_type = str(hice_type_arr[0])
        hice_label = HICE_LABELS.get(hice_type, hice_type)
        hice_color = HICE_COLORS.get(hice_type, "#6b7280")
    else:
        hice_type = None
        hice_label = None
        hice_color = None

    highlight_spans = {}
    for step_id, color in [
        ("structural_gate", "#4f46e5"),
        ("health_mask", "#2563eb"),
        ("targeting_mask", "#dc2626"),
        ("phrase_mask", "#7c3aed"),
        ("soft_health", "#059669"),
        ("proximity", "#0891b2"),
        ("bystander", "#d97706"),
    ]:
        for s in steps:
            if s["id"] == step_id:
                for m in s.get("matches", []):
                    key = (m["start"], m["end"])
                    if key not in highlight_spans:
                        highlight_spans[key] = []
                    highlight_spans[key].append({"step_id": step_id, "color": color, "label": s["label"]})

    return {
        "text": text,
        "text_lower": lower,
        "steps": steps,
        "coupling": coupling,
        "bystander_flagged": bystander_flagged,
        "is_hice": is_hice,
        "hice_type": hice_type,
        "hice_label": hice_label,
        "hice_color": hice_color,
        "highlight_spans": {f"{k[0]}:{k[1]}": v for k, v in highlight_spans.items()},
    }


# ── Routes ────────────────────────────────────────────────────────────
@app.get("/health")
async def health():
    return {"status": "ok"}


@app.get("/", response_class=HTMLResponse)
async def dashboard(request: Request):
    top_cat = max(categories, key=lambda c: categories[c]["count"]) if categories else None

    return templates.TemplateResponse("dashboard.html", {
        "request": request,
        "total_events": total_events,
        "total_hice": total_hice,
        "fatal_pct": round(total_hice / max(total_events, 1) * 100, 1),
        "top_cat": categories.get(top_cat) if top_cat else None,
        "regions_affected": len(data["geo"]),
        "total_fatalities": sum(r["fatalities"] for r in data["records"]),
        "date_min": date_min,
        "date_max": date_max,
        "categories": categories,
        "overview_pie": overview_data[0],
        "overview_kw": overview_data[1],
        "overview_actor": overview_data[2],
        "overview_evt": overview_data[3],
        "geo_data": geo_data,
        "temporal_trend": temporal_data[0],
        "temporal_cat": temporal_data[1],
        "temporal_cum": temporal_data[2],
        "risk_severity": risk_data[0],
        "risk_matrix": risk_data[1],
        "risk_vuln": risk_data[2],
        "risk_table": risk_data[3],
        "records": json.dumps(records_data),
        "hice_colors": json.dumps(HICE_COLORS),
        "hice_labels": json.dumps(HICE_LABELS),
    })


@app.post("/simulate")
async def simulate(request: Request):
    body = await request.json()
    text = body.get("text", "")
    result = simulate_pipeline(text)
    return result


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=8000, reload=True)
