import json
import os

notebook_path = '/Users/admin/Github_Project/Myanmar-conflict-observatory/notebooks/NLP_Extraction_Assessment.ipynb'

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# Find the logic-definition cell
for cell in nb['cells']:
    if cell.get('id') == 'logic-definition':
        cell['source'] = [
            "def local_extract_hice_robust(df):\n",
            "    \"\"\"Standalone implementation of the robust HICE framework (Purified v3).\"\"\"\n",
            "    notes = df['notes'].fillna('').str.lower()\n",
            "    \n",
            "    # A. High-Signal Health Ontology\n",
            "    health_terms = [\n",
            "        r'\\bhospital(s)?\\b', r'\\bclinic(s)?\\b', r'\\bhealth center(s)?\\b',\n",
            "        r'\\brural health center(s)?\\b', r'\\brhc\\b', r'\\bmedical facility\\b',\n",
            "        r'\\bhealth facility\\b', r'\\btreatment center\\b', r'\\bdoctor(s)?\\b', \n",
            "        r'\\bnurse(s)?\\b', r'\\bhealth worker(s)?\\b', r'\\bmedic(s)?\\b',\n",
            "        r'\\bmedical staff\\b', r'\\bambulance(s)?\\b', r'\\bmedical supplies\\b',\n",
            "        r'\\bworld health organization\\b', r'\\bunicef\\b', r'\\bmsf\\b', r'\\bicrc\\b',\n",
            "        r'\\bmedicine\\b.{0,20}\\b(shortage|destroyed|looted|burned|seized)\\b',\n",
            "        r'\\bpatient(s)?\\b.{0,15}\\b(injured|treated|killed|arrested|wounded)\\b'\n",
            "    ]\n",
            "    health_mask = notes.str.contains('|'.join(health_terms), regex=True)\n",
            "    \n",
            "    # B. Action & Targeting Masks (Expanded Passive Voice)\n",
            "    targeting_mask = notes.str.contains(r'\\b(target(ed|ing)?|fired upon|opened fire on|hit by|raided|occupied)\\b', regex=True)\n",
            "    action_phrases = [\n",
            "        r'\\b(set fire to)\\b',\n",
            "        r'\\b(was|were|had been) (destroyed|burned|attacked|looted)\\b',\n",
            "        r'\\b(reportedly|allegedly) (attacked|targeted)\\b',\n",
            "        r'\\bwas shot\\b', r'\\bwas arrested\\b',\n",
            "        r'\\b(was forced to close|suspended operations|came under fire|sustained damage|was struck by|had to evacuate|was displaced|forced to flee)\\b'\n",
            "    ]\n",
            "    phrase_mask = notes.str.contains('|'.join(action_phrases), regex=True)\n",
            "\n",
            "    # C. Bidirectional Proximity Linking\n",
            "    attack_terms = r'(?:attack|burn|destroy|shell|raid|arrest|target|strike|fire|hit)'\n",
            "    health_infra = r'(?:hospital|clinic|health center|doctor|nurse|medic|medical(?: facility| team| staff))'\n",
            "    proximity_pattern = rf'({health_infra}.{{0,45}}{attack_terms})|({attack_terms}.{{0,45}}{health_infra})'\n",
            "    proximity_mask = notes.str.contains(proximity_pattern, regex=True)\n",
            "    \n",
            "    # D. Constrained Soft Health\n",
            "    soft_health_mask = notes.str.contains(r'\\b(injured|wounded|killed|dead)\\b.{0,20}\\b(patient|doctor|nurse|medic|staff)\\b', regex=True)\n",
            "\n",
            "    # E. ACLED Structured Filter\n",
            "    attack_sub = ['Attack', 'Shelling/artillery/missile attack', 'Air/drone strike', 'Abduction/forced disappearance', 'Arrests', 'Looting/property destruction']\n",
            "    violent_ev = ['Violence against civilians', 'Battles', 'Explosions/Remote violence']\n",
            "    structure_mask = (df['sub_event_type'].isin(attack_sub)) | (df['event_type'].isin(violent_ev))\n",
            "    \n",
            "    # F. Robust Confidence Scoring\n",
            "    actor_presence = df['actor1'].notna().astype(int)\n",
            "    interaction_boost = (proximity_mask.astype(int) + targeting_mask.astype(int) + phrase_mask.astype(int)).clip(upper=2)\n",
            "    confidence = (interaction_boost * 2) + (health_mask.astype(int) * 2) + (soft_health_mask.astype(int) * 2) + actor_presence\n",
            "    \n",
            "    # G. Bystander Disambiguation Filter (Negative Gate)\n",
            "    enumeration_fp = notes.str.contains(r'(civilians?|villagers?|residents?).{0,50}(doctor|nurse|medic|patient)', regex=True) & \\\n",
            "                     ~notes.str.contains(r'(doctor|nurse|medic|health worker).{0,40}(killed|shot|arrested|abducted)', regex=True)\n",
            "    hospital_bystander = notes.str.contains(r'\\b(taken|sent|rushed|brought|admitted|transfer|transport|arrive|flee|arrive)\\b.{0,20}\\b(to|at|in|near).{0,15}\\b(hospital|clinic|facility|dispensary)\\b', regex=True) & \\\n",
            "                         ~notes.str.contains(r'(hospital|clinic|facility).{0,40}(attack|bomb|shell|destroy|burn|raid|strike)', regex=True)\n",
            "\n",
            "    fp_mask = enumeration_fp | hospital_bystander\n",
            "\n",
            "    # H. Two-Tier Confidence Architecture (Final Pure Gating)\n",
            "    event_coupling = (proximity_mask | phrase_mask | soft_health_mask | targeting_mask) & ~fp_mask\n",
            "    strong_signal = (proximity_mask | targeting_mask) & ~fp_mask\n",
            "    \n",
            "    # Two-Tier Confidence Architecture\n",
            "    tier1_mask = (health_mask | proximity_mask) & event_coupling & ((confidence >= 4) | strong_signal)\n",
            "    tier2_mask = health_mask & structure_mask & event_coupling & ~tier1_mask & ~fp_mask\n",
            "    \n",
            "    return tier1_mask | tier2_mask\n",
            "\n",
            "def local_classify_hice_robust(df):\n",
            "    \"\"\"Robust 5-Class classification with final category validation patches.\"\"\"\n",
            "    notes = df['notes'].fillna('').str.lower()\n",
            "    infra_markers = r'\\b(hospital|clinic|pharmacy|dispensary|health center|medical center|medical facility|health facility|treatment center)\\b'\n",
            "    staff_markers = r'\\b(doctor|nurse|midwife|surgeon|medic|medical staff|health worker)\\b'\n",
            "    access_markers = r'\\b(closed|abandoned|no access|denied access|blocked)\\b'\n",
            "    \n",
            "    # Proximity Violence (PV-HICE) routing\n",
            "    attack_terms = r'(?:attack|burn|destroy|shell|raid|arrest|target|strike|fire|hit)'\n",
            "    health_infra = r'(?:hospital|clinic|health center|doctor|nurse|medic|medical(?: facility| team| staff))'\n",
            "    proximity_pattern = rf'({health_infra}.{{0,45}}{attack_terms})|({attack_terms}.{{0,45}}{health_infra})'\n",
            "    proximity_mask = notes.str.contains(proximity_pattern, regex=True)\n",
            "    direct_action = notes.str.contains(r'\\b(target(ed|ing)?|fired upon|opened fire on|hit( by)?|struck( by)?|raided|occupied|destroyed|burned|attacked|looted|damaged|bomb(ed|s)?|shell(ed|s)?|airstrike|assaulted)\\b', regex=True)\n",
            "    pv_hice = proximity_mask & ~direct_action\n",
            "\n",
            "    is_infra = notes.str.contains(infra_markers, regex=True)\n",
            "    is_staff = notes.str.contains(staff_markers, regex=True)\n",
            "    is_access = notes.str.contains(access_markers, regex=True) | pv_hice\n",
            "    \n",
            "    # Priorities: Personnel Harm > Access Disruption > Systemic > Infrastructure > Humanitarian\n",
            "    pers_harm = notes.str.contains(r'\\b(killed|arrested|shot|abducted|beaten)\\b.{0,15}\\b(doctor|nurse|medic|midwife|staff)\\b', regex=True)\n",
            "    \n",
            "    conditions = [pers_harm, is_access, is_infra & is_staff, is_infra & ~is_staff, is_staff & ~is_infra]\n",
            "    choices = ['personnel_targeting', 'access_disruption', 'systemic_attack', 'infrastructure_damage', 'personnel_targeting']\n",
            "    return np.select(conditions, choices, default='humanitarian_disruption')\n"
        ]

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)
